version: "3.3"
services:

  # MQTT 
  mqtt:
    image: eclipse-mosquitto
    hostname: mqtt
    container_name: mqtt
    expose:
      - "10003"
    ports:
      - "10003:10003"
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - /mosquitto/data
      - /mosquitto/log
    networks:
      - default

      
  # cluster-level mongoDB
  mongo:
    image: mongo:3.6
    container_name: mongo
    hostname: mongo
    ports:
      - "10007:10007"
    volumes:
      - 'mongodb_data:/mongodb'
    command: mongod --port 10007



# Cluster Manager
  cluster_manager:
    image: cluster_manager
    build: cluster-manager/
    container_name: cluster_manager
    hostname: cluster_manager
    expose:
      - "10000"
      - "10001"
    ports:
      - "10000:10000"
      - "10001:10001"
    environment:
      - MY_PORT=10000
      - SYSTEM_MANAGER_URL=${SYSTEM_MANAGER_URL}
      - SYSTEM_MANAGER_PORT=10000
      - CLUSTER_MONGO_URL=mongo
      - CLUSTER_MONGO_PORT=10007
      - CLUSTER_SCHEDULER_URL=cluster_scheduler
      - CLUSTER_SCHEDULER_PORT=10005
      - MQTT_BROKER_URL=mqtt
      - MQTT_BROKER_PORT=10003
      - CLUSTER_NAME=${CLUSTER_NAME}
      - CLUSTER_LOCATION=${CLUSTER_LOCATION}
      - CLUSTER_PUBLIC_IP=${MYIP}
      - CLUSTER_PRIVATE_IP=192.168.178.79
    depends_on:
      - mongo
      - mqtt
      - cluster_scheduler


  # Cluster Scheduler
  cluster_scheduler:
    image: cluster_scheduler
    build: cluster-scheduler/
    container_name: cluster_scheduler
    hostname: cluster_scheduler
    expose:
      - "10005"
    ports:
      - "10005:10005"
    environment:
      - MY_PORT=10005
      - CLUSTER_MANAGER_URL=cluster_manager
      - CLUSTER_MANAGER_PORT=10000
      - CLUSTER_MONGO_URL=mongo
      - CLUSTER_MONGO_PORT=10007
      - REDIS_ADDR=redis://:clusterRedis@redis:6379
    depends_on:
      - redis
      - mongo


  # Redis for the Cluster Scheduler as Job Queue
  redis:
    image: redis
    hostname: redis
    container_name: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
    command: redis-server --requirepass clusterRedis


  prometheus:
    image: prom/prometheus
    container_name: prometheus
    hostname: prometheus
    ports:
      - 10009:9090
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    depends_on:
      - cluster_manager


volumes:
  mongodb_data:
    driver: local
