version: "3.3"

services:

  # System Manager REST API of Root Orchestrator
  system_manager:
    image: system_manager
    build: system-manager-python/
    hostname: system_manager
    container_name: system_manager
    expose:
      - "10000"
    ports:
      - "10000:10000"
    depends_on:
      - mongo_root
      - cloud_scheduler
      - root_service_manager
    environment:
      - CLOUD_MONGO_URL=mongo
      - CLOUD_MONGO_PORT=10007
      - CLOUD_SCHEDULER_URL=cloud_scheduler
      - CLOUD_SCHEDULER_PORT=10004
      - NET_PLUGIN_URL=root_service_manager
      - NET_PLUGIN_PORT=10099


  # MongoDB in Root Orchestrator
  mongo_root:
    image: mongo:3.6
    container_name: mongo
    hostname: mongo
    ports:
      - "10007:10007"
    expose:
      - "10007"
    volumes:
      - 'mongodb_data:/mongodb'
    command: mongod --port 10007

  # cluster-level mongoDB
  mongo_rootnet:
    image: mongo:3.6
    container_name: mongo_net
    hostname: mongo_net
    ports:
      - "10008:10008"
    volumes:
      - 'mongodb_net_data:/mongodb'
    command: mongod --port 10008


  # Cluster Manager
  root_service_manager:
    image: ghcr.io/oakestra/oakestra-net/root-service-manager:v0.04.arm.experimental
    container_name: root_service_manager
    hostname: root_service_manager
    expose:
      - "10099"
    ports:
      - "10099:10099"
    environment:
      - MY_PORT=10099
      - SYSTEM_MANAGER_URL=system_manager
      - SYSTEM_MANAGER_PORT=10000
      - CLOUD_MONGO_URL=mongo_net
      - CLOUD_MONGO_PORT=10008
    depends_on:
      - mongo_rootnet


  # Redis for the Cloud Scheduler
  redis:
    image: redis
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass cloudRedis


  grafana:
    image: grafana/grafana
    hostname: grafana
    container_name: grafana
    ports:
      - 80:3000


  # Cloud Scheduler
  cloud_scheduler:
    image: cloud_scheduler
    build: cloud-scheduler/
    container_name: cloud_scheduler
    hostname: cloud_scheduler
    expose:
      - "10004"
    ports:
      - "10004:10004"
    environment:
      - MY_PORT=10004
      - SYSTEM_MANAGER_URL=system_manager
      - SYSTEM_MANAGER_PORT=10000
      - CLOUD_MONGO_URL=mongo
      - CLOUD_MONGO_PORT=10007
      - REDIS_ADDR=redis://:cloudRedis@redis:6379
    depends_on:
      - redis
      - mongo_root


volumes:
  mongodb_data:
    driver: local
  mongodb_net_data:
    driver: local
