version: "2.4"

services:

  # System Manager REST API of Root Orchestrator
  system_manager:
    image: system_manager
    build: system-manager-python/
    hostname: system_manager
    container_name: system_manager
    networks:
      root_net:
        ipv4_address: 192.168.128.2
        ipv6_address: 2001:db8:a::2
    expose:
      - "10000"
    ports:
      - "10000:10000"
    depends_on:
      - mongo_root
      - cloud_scheduler
      - root_service_manager
    environment:
      - CLOUD_MONGO_URL=[2001:db8:a::5]
      - CLOUD_MONGO_PORT=10007
      - CLOUD_SCHEDULER_URL=[2001:db8:a::7]
      - CLOUD_SCHEDULER_PORT=10004
      - NET_PLUGIN_URL=[2001:db8:a::3]
      - NET_PLUGIN_PORT=10099
    # enable IPv6
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0



  # MongoDB in Root Orchestrator
  mongo_root:
    image: mongo:3.6
    container_name: mongo
    hostname: mongo
    networks:
      root_net:
        ipv4_address: 192.168.128.5
        ipv6_address: 2001:db8:a::5
    ports:
      - "10007:10007"
    expose:
      - "10007"
    volumes:
      - 'mongodb_data:/mongodb'
    command: mongod --port 10007 --ipv6
    # enable IPv6
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

  # cluster-level mongoDB
  mongo_rootnet:
    image: mongo:3.6
    container_name: mongo_net
    hostname: mongo_net
    networks:
      root_net:
        ipv4_address: 192.168.128.4
        ipv6_address: 2001:db8:a::4
    ports:
      - "10008:10008"
    volumes:
      - 'mongodb_net_data:/mongodb'
    command: mongod --port 10008 --ipv6
    # enable IPv6
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

  # Cluster Manager
  root_service_manager:
    #image: ghcr.io/oakestra/oakestra-net/root-service-manager:v0.04.amd64.experimental
    image: root-service-manager
    build: service-manager
    container_name: root_service_manager_local
    hostname: root_service_manager
    networks:
      root_net:
        ipv4_address: 192.168.128.3
        ipv6_address: 2001:db8:a::3
    expose:
      - "10099"
    ports:
      - "10099:10099"
    environment:
      - MY_PORT=10099
      - SYSTEM_MANAGER_URL=[2001:db8:a::2]
      - SYSTEM_MANAGER_PORT=10000
      - CLOUD_MONGO_URL=[2001:db8:a::4]
      - CLOUD_MONGO_PORT=10008
    depends_on:
      - mongo_rootnet
    # enable IPv6
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

  # Redis for the Cloud Scheduler
  redis:
    image: redis
    hostname: redis
    container_name: redis
    networks:
      root_net:
        ipv4_address: 192.168.128.8
        ipv6_address: 2001:db8:a::8
    ports:
      - "6379:6379"
    command: redis-server --requirepass cloudRedis
    # enable IPv6
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
   
  grafana:
    image: grafana/grafana
    hostname: grafana
    container_name: grafana
    networks:
      root_net:
        ipv4_address: 192.168.128.9
        ipv6_address: 2001:db8:a::9
    ports:
      - 80:3000
    # enable IPv6
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

  # Cloud Scheduler
  cloud_scheduler:
    image: cloud_scheduler
    build: cloud-scheduler/
    container_name: cloud_scheduler
    hostname: cloud_scheduler
    networks:
      root_net:
        ipv4_address: 192.168.128.7
        ipv6_address: 2001:db8:a::7
    expose:
      - "10004"
    ports:
      - "10004:10004"
    environment:
      - MY_PORT=10004
      - SYSTEM_MANAGER_URL=[2001:db8:a::2]
      - SYSTEM_MANAGER_PORT=10000
      - CLOUD_MONGO_URL=[2001:db8:a::5]
      - CLOUD_MONGO_PORT=10007
      - REDIS_ADDR=redis://:cloudRedis@redis:6379
    depends_on:
      - redis
      - mongo_root
    # enable IPv6
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0

volumes:
  mongodb_data:
    driver: local
  mongodb_net_data:
    driver: local

networks:
  root_net:
    name: root_net
    enable_ipv6: true
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      config:
        - subnet: 2001:db8:a::/64
          gateway: 2001:db8:a::1
        - subnet: 192.168.128.0/24
          gateway: 192.168.128.1
