name: Golang node enigne artifacts

on:
  push:
    branches:
      - develop

jobs:
  releases-matrix:
    name: Release Go Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # build and publish in parallel: linux/386, linux/amd64, linux/arm64, windows/386, windows/amd64, darwin/amd64, darwin/arm64
        goos: [linux]
        goarch: [amd64, arm64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 0.4.1

      # Prepare release package using go release 1.31
      - name: Go release
        uses: wangyoucao577/go-release-action@v1.31
        with:
          github_token: ${{ secrets.PACKAGES_TOKEN }}
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: "https://go.dev/dl/go1.19.1.linux-amd64.tar.gz"
          project_path: "./go_node_engine"
          binary_name: "NodeEngine"
          release_tag: alpha-${{ steps.previoustag.outputs.tag }}
          asset_name: NodeEngine_${{ matrix.goarch }}
          extra_files: go_node_engine/build/install.sh go_node_engine/build/configure-gpu.sh
          overwrite: TRUE

